#Can use a YAML file instead of the properties file for configuration. Just need to delete the properties file.
spring:
  application:
    name: PieRouletteYAML
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    spring.jap.database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 5000